### PR TITLE
Extend parser.

### PR DESCRIPTION
**Pull request by wilx**
Extend Open Graph metadata parser to deal with type specific metadata
and also with arrays of metadata.

### CODE REVIEW

**Comment by lestrrat** [comment]
ho ho, it's been so long. I need to put this in a CI first :D

**Comment by lestrrat** [comment]
Please give me roughly 24 hrs. I may or may not be able to get to this today (in Japan time)

**Comment by lestrrat** [comment]
Oh wow, wait a second,  I got notification for a 2016 PR just today?! HOW THE F...

**Comment by lestrrat** [comment]
So I apologize for not noticing this PR sooner, and you probably think I'm a tool for replying to you now. I guess I can't say anything to that except to bang my head against the wall in self-disgust.

Now, upon actually attempt to merge your PR against this repo, the tests failed, and I really don't have much else to go on with right now. If you are interested, please see my topic/pr-1 branch, which has a rebased version of your PR.

If you happen to still be interested in seeing this changed, please reopen the PR. Thank you!

**Comment by wilx** [comment]
No problem. I will take a look at the tests.

**Pull request closed without merging**
